language: swift
xcode_workspace: RRemoteConfig.xcworkspace
xcode_scheme: Tests
osx_image: xcode10.2

before_install:
- gem update fastlane cocoapods xcov --no-document
- pod repo update

script: fastlane ci

# FIXME: codecov cannot read the Xcode 10 generated code coverage file
#after_success:
#  - bash <(curl -s https://codecov.io/bash) -J RRemoteConfig -X gcov -X coveragepy -f '!*.xml'
