language: swift
xcode_workspace: RRemoteConfig.xcworkspace
xcode_scheme: Tests
osx_image: xcode10.2

before_install:
- gem install xcov
- gem update fastlane cocoapods xcov --no-document
- pod repo update

script: fastlane ci
